[project]
name = "susa"
version = "0.1.0"
description = "SUSA Unified Systems API - programmatically work with machines"
readme = "README.md"
authors = [
    { name = "Noam Zaks", email = "noam@noamzaks.com" }
]
requires-python = ">=3.14"
dependencies = [
    "libvirt-python>=12.6.0",
    "pexpect>=4.9.0",
    "pydantic>=2.13.4",
    "pydantic-libvirt",
    "pydantic-xml>=2.21.1",
    "typing-extensions>=4.16.0",
]

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
pydantic-libvirt = { git = "https://github.com/noamzaks/pydantic-libvirt" }

[tool.mypy]
strict = true
files = ["src", "tests"]
enable_error_code = ["explicit-override"]
follow_untyped_imports = true
untyped_calls_exclude = ["IPython"]

[tool.pytest.ini_options]
addopts = ["--dist", "loadgroup"]

[tool.ruff]
ignore = ["UP035"]

[dependency-groups]
dev = [
    "ipython>=9.16.1",
    "mypy>=2.3.0",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-snapshot>=0.9.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.16.3",
    "types-pexpect>=4.9.0.20260518",
]
