from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pydantic

from susa.libvirt.disk_model import DiskModel
from susa.libvirt.interface_model import InterfaceModel
from susa.libvirt.machine import LVMachine, LVSnapshot
from susa.libvirt.machine_model import MachineModel, SnapshotModel
from susa.libvirt.network import LVNetwork
from susa.libvirt.network_model import NetworkModel

# The JSON schemas of the models and the entities' states, shipped as `<name>.schema.json` next to this file (they're
# generated by running this module, which `scripts/release.sh` does before building).
TYPES: list[type[Any]] = [
    MachineModel,
    NetworkModel,
    DiskModel,
    InterfaceModel,
    SnapshotModel,
    LVMachine,
    LVNetwork,
    LVSnapshot,
]
DIRECTORY = Path(__file__).parent


def generate(directory: Path = DIRECTORY) -> None:
    for t in TYPES:
        schema = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            **pydantic.TypeAdapter(t).json_schema(),
            "title": t.__name__,
        }
        (directory / f"{t.__name__}.schema.json").write_text(
            json.dumps(schema, indent=2) + "\n"
        )
